name: dispenser_ui
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.8.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  share: ^0.6.1
  path_provider: ^1.6.5
  build_runner: ^1.0.0
  build_test: ^0.10.3
  json_serializable: ^2.0.0
  intl: ^0.15.7
  sqflite: ^1.3.0
  path: ^1.6.4
  provider: ^4.0.5
  http: ^0.12.0+4

  auto_size_text: ^1.1.2
  dropdown_formfield: ^0.1.1
  rflutter_alert: ^1.0.3
  flutter_staggered_grid_view: ^0.2.7
  numberpicker: ^1.2.0
  flutter_speed_dial: ^1.2.5

flutter:
  uses-material-design: true

  assets:
    - assets/inventory/1.jpeg
    - assets/inventory/2.jpeg
    - assets/inventory/3.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
