name: dispenser_ui
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  rflutter_alert: ^1.0.3
  flutter_speed_dial: ^1.2.5
  flutter_counter: ^1.0.3
  dropdown_formfield: 0.1.1
  flutter_speed_dial_material_design: 1.2.0


flutter:
  uses-material-design: true

  assets:
    - assets/inventory/storage.jpg
    - assets/inventory/fridge.jpg
    - assets/inventory/freezer.jpg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
